from pymongo import MongoClient

# Connect and find/create database
client = MongoClient('localhost', 27017)
db = client['IxP']

# Init collection
user_collection = db['user']
route_collection = db['route']
location_collection = db['location']


"""
Grab logged-in user info

@param: user_id
"""
def get_logged_user(username, password):
    # query the user document based on the user_id
    user_info = user_collection.find_one({"username": username})
    p = user_info['password']

    if password == p:
        print('password matches')
        return user_info, 200

    # return the query as a json
    print('password does not match')
    return {"error": "Wrong login info"}, 403


"""
Grab routes pertaining to the user

@param: route_id
"""
def get_routes(route_id):
    # query the route based on the route_id
    # must be accessed by get_logged_user

    # return an array of routes
    return


"""
Grabs available locations for travel 
"""
def get_locations(location_id):
    # query all locations based on the location_id

    # return the array of locations 
    return


"""
User Collection:

{
	username: String,
	profilePicture: BLOB,
	password: Hashed password,
	firstName: String,
	lastName: String,
	routes: [route-id]
}

Route Collection:

{
	route-id: (generated by mongodb),
	locations: [{location-id: Number,  dayOfTravel: String}]
}

Location Collection:

{
	location-id: (generated by mongodb),
	name: String,
	city: String,
	address: String,
	latitude: Number,
	longitude: Number,
	rating: Number,
	comments: [{user: String, comment: String}]
}



"""